import { StyleSheet } from "@react-pdf/renderer";

export const styles = StyleSheet.create({
	page: {
		flexDirection: "column",
		backgroundColor: "#FFF",
		fontFamily: "Inter",
	},
	head: {
		display: "flex",
		flexDirection: "row",
		justifyContent: "space-between",
		alignItems: "flex-start",
		padding: "4.36vw 3.36vw",
	},
	headRight: {
		display: "flex",
		flexDirection: "column",
		justifyContent: "flex-start",
		gap: "6pt",
		flex: 1,
	},
	headRightUp: {
		display: "flex",
		justifyContent: "space-between",
		alignItems: "center",
		flexDirection: "row",
	},
	headRightBottom: {
		display: "flex",
		justifyContent: "space-between",
		flexDirection: "row",
		gap: "6pt",
	},
	partInfo: {
		width: "278pt",
	},
	partDate: {
		width: "139pt",
	},
	logo: {
		width: 77.25,
		height: 77.25,
		marginRight: "8pt",
		objectFit: "contain",
	},
	headInfo: {
		width: "42vw",
		justifyContent: "center",
		alignItems: "flex-start",
		marginRight: "18pt",
	},
	headInfoTitle: {
		fontFamily: "Inter",
		fontSize: "16pt",
		fontWeight: 700,
		letterSpacing: 0.1,
		color: "#333333",
		lineHeight: 1.5,
	},
	headInfoInvoiceId: {
		fontFamily: "Inter",
		fontSize: "12pt",
		fontWeight: 400,
		letterSpacing: 0.1,
		color: "#333333",
	},
	headInfoAddress: {
		fontSize: "10pt",
		fontWeight: 400,
		letterSpacing: 0.1,
		color: "#656565",
		lineHeight: 1.8,
		marginTop: "4pt",
		marginBottom: "4pt",
	},
	headInfoPhone: {
		fontFamily: "Inter",
		fontSize: "12pt",
		fontWeight: 400,
		letterSpacing: 0.1,
		color: "#656565",
		lineHeight: 1.5,
	},
	tableHeader: {
		width: "32%",
	},
	tableHeaderRow: {
		display: "flex",
		flexDirection: "row",
		justifyContent: "space-between",
		width: "139pt",
		gap: "4px",
	},
	tableHeader1: {
		width: "80pt",
		height: "22px",
	},
	tableHeader2: {
		width: "4pt",
		height: "22px",
		margin: "0 4pt",
	},
	tableHeader3: {
		width: "80pt",
		height: "22px",
	},
	tableHeader3Bold: {
		width: "80pt",
		height: "22px",
	},
	textTableHeader: {
		fontSize: "10pt",
		fontWeight: 400,
		lineHeight: 1.5,
		letterSpacing: 0.1,
		color: "#656565",
	},
	textTableHeaderRight: {
		fontSize: "12pt",
		fontWeight: 400,
		lineHeight: 1.5,
		letterSpacing: 0.1,
		color: "#656565",
		textAlign: "right",
	},
	textBoldTableHeader: {
		fontFamily: "Inter",
		fontSize: "12pt",
		fontWeight: 900,
		lineHeight: 1.5,
		letterSpacing: 0.1,
		color: "#656565",
	},
	textBoldTableHeaderRight: {
		fontFamily: "Inter",
		fontSize: "12pt",
		fontWeight: 900,
		lineHeight: 1.5,
		letterSpacing: 0.1,
		color: "#656565",
		textAlign: "right",
	},
	headerLine: {
		width: "93.2%",
		height: "1pt",
		backgroundColor: "#000000",
		margin: "-8pt 3.36vw 0",
	},
	body: {
		width: "90.2%",
		padding: "0 4.9vw",
	},
	bodyInfo: {
		flexDirection: "column",
		justifyContent: "center",
		gap: "4pt",
		margin: "16pt 0",
	},
	bodyInfoData: {
		flexDirection: "column",
		justifyContent: "center",
	},
	bodyInfoDataTitle: {
		fontFamily: "Inter",
		fontWeight: "bold",
		fontSize: "12pt",
		lineHeight: 1.5,
		color: "#656565",
	},
	bodyInfoDataContent: {
		fontWeight: "normal",
		fontSize: "12pt",
		lineHeight: 1.5,
		color: "#656565",
	},
	bodyTable: {
		flexDirection: "row",
		width: "100vw",
	},
  bodyTableRow: {
    flexDirection: "column",
    justifyContent: "space-between",
    width: "100%",
  },
	bodyTableRowTop: {
		backgroundColor: "#DADAF2",
		padding: "4pt 4px",
		borderTop: "0.5pt solid #656565",
		borderRight: "0.25pt solid #656565",
		borderBottom: "0.25pt solid #656565",
		borderLeft: "0.5pt solid #656565",
	},
	bodyTableRowBottom: {
		padding: "4pt 5px",
		borderTop: "0.25pt solid #656565",
		borderRight: "0.25pt solid #656565",
		borderBottom: "0.5pt solid #656565",
		borderLeft: "0.5pt solid #656565",
	},
	bodyTableTextHeader: {
		fontWeight: "medium",
		fontSize: "6pt",
		lineHeight: 1.5,
		color: "#333333",
	},
	bodyTableTextDetail: {
		fontWeight: "normal",
		fontSize: "5pt",
		lineHeight: 1.5,
		color: "#656565",
	},
	bodyTableTextDetailRight: {
		fontWeight: "normal",
		fontSize: "7pt",
		lineHeight: 1.5,
		color: "#656565",
		textAlign: "right",
	},
	bodyTableTextDetailRightRed: {
		fontWeight: "normal",
		fontSize: "7pt",
		lineHeight: 1.5,
		color: "#DF6262",
		textAlign: "right",
	},
	netPayment: {
		flexDirection: "row",
		justifyContent: "flex-end",
		gap: "4pt",
		marginBottom: "4pt"
	},
	netPaymentText1: {
		fontWeight: "normal",
		fontSize: "12pt",
		lineHeight: 1.5,
		color: "#656565",
		width: "20vw",
	},
	netPaymentText2: {
		fontWeight: "normal",
		fontSize: "12pt",
		lineHeight: 1.5,
		color: "#656565",
	},
	netPaymentText3: {
		fontFamily: "Inter",
		fontSize: "12pt",
		fontWeight: 700,
		lineHeight: 1.5,
		color: "#656565",
		width: "20vw",
	},
  invoiceFooter: {
    display: "flex",
		flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "flex-start",
		gap: "24pt",
		marginTop: "36pt",
  },
  invoiceFooterLeft: {},
  invoiceFooterRight: {}
});